CREATE TABLE IF NOT EXISTS `tochukwu_learning_followup_campaigns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `campaign_uuid` VARCHAR(64) NOT NULL,
  `account_id` BIGINT NOT NULL,
  `course_slug` VARCHAR(120) NOT NULL,
  `batch_key` VARCHAR(64) NOT NULL,
  `batch_label` VARCHAR(120) NULL,
  `learner_name` VARCHAR(180) NULL,
  `recipient_name` VARCHAR(180) NULL,
  `recipient_email` VARCHAR(220) NOT NULL,
  `enrollment_source` VARCHAR(40) NOT NULL,
  `enrolled_at` DATETIME NULL,
  `batch_start_at` DATETIME NOT NULL,
  `campaign_started_at` DATETIME NOT NULL,
  `campaign_ends_at` DATETIME NOT NULL,
  `last_activity_at` DATETIME NULL,
  `last_reminder_at` DATETIME NULL,
  `next_reminder_at` DATETIME NOT NULL,
  `reminder_count` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `stopped_reason` VARCHAR(80) NULL,
  `locked_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_learning_followup_campaign_uuid` (`campaign_uuid`),
  UNIQUE KEY `uniq_learning_followup_learner_course_batch` (`account_id`, `course_slug`, `batch_key`),
  KEY `idx_learning_followup_due` (`status`, `next_reminder_at`),
  KEY `idx_learning_followup_recipient` (`recipient_email`, `last_reminder_at`),
  KEY `idx_learning_followup_lock` (`status`, `locked_at`),
  KEY `idx_learning_followup_course_batch` (`course_slug`, `batch_key`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tochukwu_learning_followup_deliveries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `delivery_uuid` VARCHAR(64) NOT NULL,
  `delivery_group_uuid` VARCHAR(64) NOT NULL,
  `campaign_id` BIGINT NOT NULL,
  `reminder_number` INT NOT NULL,
  `recipient_email` VARCHAR(220) NOT NULL,
  `subject` VARCHAR(255) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `attempts` INT NOT NULL DEFAULT 0,
  `provider_message_id` VARCHAR(500) NULL,
  `last_error` VARCHAR(1000) NULL,
  `snapshot_json` LONGTEXT NULL,
  `last_attempt_at` DATETIME NULL,
  `sent_at` DATETIME NULL,
  `delivered_at` DATETIME NULL,
  `opened_at` DATETIME NULL,
  `bounced_at` DATETIME NULL,
  `clicked_at` DATETIME NULL,
  `resumed_at` DATETIME NULL,
  `provider_event` VARCHAR(40) NULL,
  `provider_event_at` DATETIME NULL,
  `provider_event_detail` VARCHAR(1000) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_learning_followup_delivery_uuid` (`delivery_uuid`),
  UNIQUE KEY `uniq_learning_followup_campaign_cycle` (`campaign_id`, `reminder_number`),
  KEY `idx_learning_followup_delivery_group` (`delivery_group_uuid`),
  KEY `idx_learning_followup_delivery_status` (`status`, `last_attempt_at`),
  KEY `idx_learning_followup_delivery_recipient` (`recipient_email`, `sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tochukwu_learning_followup_recipient_preferences` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `recipient_email` VARCHAR(220) NOT NULL,
  `course_slug` VARCHAR(120) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'active',
  `paused_at` DATETIME NULL,
  `resumed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_learning_followup_preference` (`recipient_email`, `course_slug`),
  KEY `idx_learning_followup_preference_status` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
