CREATE TABLE IF NOT EXISTS `tochukwu_course_payment_refunds` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `refund_uuid` VARCHAR(64) NOT NULL,
  `source_type` VARCHAR(24) NOT NULL,
  `payment_uuid` VARCHAR(100) NOT NULL,
  `course_slug` VARCHAR(120) NULL,
  `batch_key` VARCHAR(64) NULL,
  `customer_name` VARCHAR(190) NULL,
  `customer_email` VARCHAR(220) NOT NULL,
  `currency` VARCHAR(12) NOT NULL,
  `amount_minor` BIGINT NOT NULL,
  `refund_method` VARCHAR(40) NOT NULL,
  `refund_reference` VARCHAR(190) NOT NULL,
  `reason` VARCHAR(1000) NOT NULL,
  `access_revoked` TINYINT(1) NOT NULL DEFAULT 1,
  `recorded_by` VARCHAR(190) NOT NULL,
  `refunded_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_tochukwu_course_refund_uuid` (`refund_uuid`),
  UNIQUE KEY `uniq_tochukwu_course_refund_payment` (`source_type`, `payment_uuid`),
  KEY `idx_tochukwu_course_refund_date` (`refunded_at`),
  KEY `idx_tochukwu_course_refund_email` (`customer_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
