CREATE TABLE IF NOT EXISTS `student_public_profiles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `profile_uuid` VARCHAR(64) NOT NULL,
  `account_id` BIGINT NOT NULL,
  `public_slug` VARCHAR(190) NOT NULL,
  `display_name` VARCHAR(180) NOT NULL,
  `professional_headline` VARCHAR(220) NULL,
  `biography` TEXT NULL,
  `country` VARCHAR(120) NULL,
  `skills_json` TEXT NULL,
  `featured_project_summary` TEXT NULL,
  `project_challenge` TEXT NULL,
  `project_solution` TEXT NULL,
  `project_learning` TEXT NULL,
  `opportunity_types_json` TEXT NULL,
  `public_profile_consent` TINYINT(1) NOT NULL DEFAULT 0,
  `profile_picture_consent` TINYINT(1) NOT NULL DEFAULT 0,
  `guardian_consent_confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `open_to_work` TINYINT(1) NOT NULL DEFAULT 0,
  `is_public` TINYINT(1) NOT NULL DEFAULT 0,
  `review_status` VARCHAR(24) NOT NULL DEFAULT 'pending',
  `review_note` TEXT NULL,
  `reviewed_by` VARCHAR(180) NULL,
  `reviewed_at` DATETIME NULL,
  `published_snapshot_json` LONGTEXT NULL,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_student_public_profiles_uuid` (`profile_uuid`),
  UNIQUE KEY `uniq_student_public_profiles_account` (`account_id`),
  UNIQUE KEY `uniq_student_public_profiles_slug` (`public_slug`),
  KEY `idx_student_public_profiles_review` (`review_status`, `updated_at`),
  KEY `idx_student_public_profiles_public` (`is_public`, `published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `student_hire_enquiries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `enquiry_uuid` VARCHAR(64) NOT NULL,
  `profile_id` BIGINT NOT NULL,
  `account_id` BIGINT NOT NULL,
  `enquirer_name` VARCHAR(180) NOT NULL,
  `organisation` VARCHAR(220) NULL,
  `enquirer_email` VARCHAR(190) NOT NULL,
  `opportunity_type` VARCHAR(60) NOT NULL,
  `timeline` VARCHAR(120) NULL,
  `budget_range` VARCHAR(120) NULL,
  `message` TEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'new',
  `delivery_status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `delivery_error` TEXT NULL,
  `admin_note` TEXT NULL,
  `ip_hash` VARCHAR(128) NULL,
  `consent_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_student_hire_enquiries_uuid` (`enquiry_uuid`),
  KEY `idx_student_hire_enquiries_profile` (`profile_id`, `created_at`),
  KEY `idx_student_hire_enquiries_account` (`account_id`, `created_at`),
  KEY `idx_student_hire_enquiries_status` (`status`, `created_at`),
  KEY `idx_student_hire_enquiries_email` (`enquirer_email`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
