CREATE TABLE IF NOT EXISTS `tochukwu_paystack_payment_events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_uuid` VARCHAR(64) NOT NULL,
  `order_uuid` VARCHAR(64) NULL,
  `provider_reference` VARCHAR(190) NULL,
  `provider_event_id` VARCHAR(190) NULL,
  `source` VARCHAR(32) NOT NULL,
  `event_type` VARCHAR(80) NOT NULL,
  `outcome` VARCHAR(40) NOT NULL,
  `provider_status` VARCHAR(40) NULL,
  `expected_amount_minor` INT NULL,
  `received_amount_minor` INT NULL,
  `expected_currency` VARCHAR(12) NULL,
  `received_currency` VARCHAR(12) NULL,
  `http_status` INT NULL,
  `error_code` VARCHAR(120) NULL,
  `error_message` VARCHAR(1000) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_tochukwu_paystack_event_uuid` (`event_uuid`),
  KEY `idx_tochukwu_paystack_event_order` (`order_uuid`, `created_at`),
  KEY `idx_tochukwu_paystack_event_reference` (`provider_reference`, `created_at`),
  KEY `idx_tochukwu_paystack_event_outcome` (`outcome`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
