CREATE TABLE IF NOT EXISTS `tochukwu_course_lifecycle_deliveries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `delivery_uuid` VARCHAR(64) NOT NULL,
  `course_slug` VARCHAR(120) NOT NULL,
  `batch_key` VARCHAR(64) NOT NULL,
  `stage` VARCHAR(40) NOT NULL,
  `stage_key` VARCHAR(190) NOT NULL,
  `recipient_key` VARCHAR(190) NOT NULL,
  `recipient_role` VARCHAR(32) NOT NULL,
  `recipient_email` VARCHAR(320) NOT NULL,
  `recipient_name` VARCHAR(180) NULL,
  `due_at` DATETIME NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `attempts` INT NOT NULL DEFAULT 0,
  `subject` VARCHAR(255) NULL,
  `snapshot_json` LONGTEXT NULL,
  `provider_message_id` VARCHAR(500) NULL,
  `last_error` VARCHAR(1000) NULL,
  `last_attempt_at` DATETIME NULL,
  `sent_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_course_lifecycle_delivery_uuid` (`delivery_uuid`),
  UNIQUE KEY `uniq_course_lifecycle_recipient_stage` (`course_slug`, `batch_key`, `stage_key`, `recipient_key`),
  KEY `idx_course_lifecycle_due` (`status`, `due_at`),
  KEY `idx_course_lifecycle_recipient` (`recipient_email`, `sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
